# Changes here will be overwritten by Copier
_commit: 0.0.1
_src_path: gh:reservoir-data/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramirez-Mondragon
author_username: edgarrmondragon
python_main_version: '3.10'
repository_name: tap-bitly
repository_namespace: edgarrmondragon
repository_provider: github.com
tap_auth_method: Bearer Token
tap_id: tap-bitly
tap_package_command_line_name: tap-bitly
tap_package_distribution_name: tap-bitly
tap_package_import_name: tap_bitly
tap_source_description: URL shortener
tap_source_id: Bitly
tap_source_name: Bitly
tap_stream_type: REST
